name: web3dart_builders
description: Extension of the web3dart package that includes the dart contract generator from abi.
version: 0.1.2
repository: https://github.com/inveker/web3dart_builders
homepage: https://github.com/inveker/web3dart_builders

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: ^2.3.1
  code_builder: ^4.4.0
  web3dart: ^3.0.1
  built_collection: ^5.1.1
  path: ^1.8.3
  dart_style: ^2.2.4
  web3_signers: ^0.2.1

dev_dependencies:
  lints: ^2.1.1
  test: ^1.21.0
  build_runner: ^2.4.9
  build_config: ^1.1.1
  build_test: ^2.1.6
